apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch
  namespace: elastic-stack
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data/elasticsearch
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  
